---

- name: install postgresql
  yum:
    name: postgresql-server
    state: latest

- name: Check if Postgres initialized
  stat:
    path: "{{ postgres_data_dir }}/PG_VERSION"
  register: r_postgres_init_dir_state

- name: Run Postgres initdb to initialize if postgres not initialized
  command: "postgresql-setup initdb"
  notify: restart postgresql
  when: not r_postgres_init_dir_state.stat.exists

- name: Setup Postgres for remote password auth
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_data_dir }}/pg_hba.conf"
  notify: restart postgresql

- name: Setup Postgres to listen on network interfaces
  lineinfile:
    dest: "{{ postgres_data_dir }}/postgresql.conf"
    line: "listen_addresses = '*'"
    insertafter: "#listen_addresses"
  notify: restart postgresql
