---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: true

- name: enable repos
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/
    mode: 0644

- name: install base tools and packages
  yum:
    name: wget
    state: latest
